config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'events#index'
  resources :events, only: [:new, :create, :index, :show]
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :send_participation_email
  belongs_to :user
  belongs_to :event

  private

  def send_participation_email
    EventMailer.event_participation(self.user, self.event).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
    # after_create :send_creation_email
    validates :start_date, presence: true
    validates :duration, numericality: { greater_than: 0, only_integer: true }
    validates :title, length: { in: 5..140 }
    validates :description, length: { in: 20..1000 }
    validates :price, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 1000 }
    validates :location, presence: true
    has_many :attendances
    has_many :users, through: :attendances
    belongs_to :admin, class_name: 'User', optional: true

    private

    # def send_creation_email
    # EventMailer.event_created(self).deliver_now
    # end
end

app/models/user.rb
class User < ApplicationRecord
    after_create :send_welcome_email
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    validates :email, presence: true, uniqueness: true
    validates :encrypted_password, presence: true
    has_many :attendances
    has_many :events, through: :attendances
    has_many :administered_events, class_name: 'Event', foreign_key: 'admin_id'

    private
    def send_welcome_email
        UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end
  def show
    @event = Event.find(params[:id])
  end
  def new
    @event = Event.new
  end
  
  def create
    @event = current_user.events.build(event_params)
    @event.admin_id = current_user.id
    if @event.save
      redirect_to @event, notice: 'L\'événement a été créé avec succès.'
    else
      render :new
    end
  end
  
  private
  
  def event_params
    params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = current_user
    end

    def edit
        @user = current_user
    end

    def update
        @user = User.find(params[:id])
      
        if @user.update(user_params)
          redirect_to @user, notice: 'Les informations de l\'utilisateur ont été mises à jour avec succès.'
        else
          render :edit
        end
    end

    private

    def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="event">
  <h3><%= event.title %></h3>
  <p>Description: <%= event.description %></p>
  <p>Date: <%= event.start_date %></p>
  <p>Lieu: <%= event.location %></p>
  <!-- Ajoutez d'autres détails de l'événement selon vos besoins -->
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">Events</h1>
  <a class="btn btn-outline-danger btn-sm" href="<%= new_event_path%>" role="button">New event</a>
  <hr class="my-4">
  <br><br>
</div>


<div id="events">
  <% if @events.any? %>
    <% @events.each do |event| %>
      <div class="event">
        <%= render partial: 'events/event', locals: { event: event } %>
        <p>
          <%= link_to "Voir cet événement", event_path(event), class: 'btn btn-primary' %>
        </p>
      </div>
    <% end %>
  <% else %>
    <p>Aucun événement trouvé.</p>
  <% end %>
</div>

app/views/events/new.html.erb
<%= form_for @event, html: { class: 'needs-validation', novalidate: '' } do |f| %>
    <div class="form-group">
      <%= f.label :title, 'Titre' %>
      <%= f.text_field :title, class: 'form-control', required: true %>
    </div>
  
    <div class="form-group">
      <%= f.label :description, 'Description' %>
      <%= f.text_area :description, class: 'form-control', required: true %>
    </div>
  
    <div class="form-group">
      <%= f.label :start_date, 'Date de début' %>
      <%= f.datetime_select :start_date, class: 'form-control', required: true %>
    </div>
  
    <div class="form-group">
      <%= f.label :duration, 'Durée (en minutes)' %>
      <%= f.number_field :duration, class: 'form-control', required: true %>
    </div>
  
    <div class="form-group">
      <%= f.label :price, 'Prix' %>
      <%= f.number_field :price, class: 'form-control', required: true %>
    </div>
  
    <div class="form-group">
      <%= f.label :location, 'Localisation' %>
      <%= f.text_field :location, class: 'form-control', required: true %>
    </div>
  
    <%= f.submit 'Créer l\'Événement', class: 'btn btn-primary' %>
  <% end %>
  <% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "erreur") %> empêché cet événement d'être sauvegardé :</h2>
    <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p><%= @event.description %></p>
<p>Location: <%= @event.location %></p>
<p>Date: <%= @event.start_date %></p>
<p>Duration: <%= @event.duration %> minutes</p>
<p>Price: <%= number_to_currency(@event.price) %></p>

<%= link_to 'Back to Events', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-turbo='false'>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">MaApp</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Accueil', root_path, class: 'nav-link active' %>
          </li>
          <% if user_signed_in? %>
            <% if user_signed_in? %>
              <%= link_to 'Créer un Événement', new_event_path, class: 'nav-link' %>
            <% end %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Mon Profil
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to 'Mon profil', user_path(current_user), class: 'dropdown-item' %></li>
                <li>
                  <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                S'inscrire / Se connecter
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to 'S\'inscrire', new_user_registration_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'Se connecter', new_user_session_path, class: 'dropdown-item' %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Modifier l'utilisateur</h1>

<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <%= link_to 'Modifier Email et Mot de Passe', edit_user_registration_path, class: 'btn btn-link' %>

  <div class="actions">
    <%= f.submit "Sauvegarder" %>
  </div>
<% end %>

<%= link_to 'Retour', user_path(@user) %>

app/views/users/show.html.erb
<h1>Profil de l'utilisateur</h1>

<div class="user-profile">
  <p><strong>Prénom :</strong> <%= @user.first_name %></p>
  <p><strong>Nom :</strong> <%= @user.last_name %></p>
  <p><strong>Email :</strong> <%= @user.email %></p>
  <p><strong>Description :</strong> <%= @user.description %></p>
</div>
<h2>Mes événements :</h2>
<% Event.all.each do |event| %>
    <% if event.admin_id == current_user.id %>
        <p><%= link_to event.title, event_path(event) %></p>
    <%end%>
<% end %>
<%= link_to 'Modifier', edit_user_path(@user), class: 'btn btn-primary' %>